<?php

use Illuminate\Database\Seeder;

class accountTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $password = bcrypt('123456');
        $faker = Faker\Factory::create('vi_VN');
        $list = [
        //  ["acc_user" => 'admin', "acc_password" => $password, "acc_email" => 'email', "rol_id" => '1'],
        //  ["acc_user" => 'customer', "acc_password" => $password, "acc_email" => 'email', "rol_id" => '2'],

        ["acc_user" => 'admin', "acc_password" => $password,
            'acc_fullname'  => '',
            'acc_sex'       => '3',
            'acc_birthday'  => $faker->dateTimeBetween('1980-01-01','2000-01-01', null),
            'acc_phonenum'  => '',
            'acc_picture'   => 'avatar.png',
            'acc_email'     => 'email', 
            'rol_id'        => '1'],
        ["acc_user" => 'customer', "acc_password" => $password,
            'acc_fullname'  => '',
            'acc_sex'       => '3',
            'acc_birthday'  => $faker->dateTimeBetween('1980-01-01','2000-01-01', null),
            'acc_phonenum'  => '',
            'acc_picture'   => 'avatar5.png',
            'acc_email'     => 'email', 
            'rol_id'        => '2'],

        ["acc_user" => 'thanh292', "acc_password" => $password,
            'acc_fullname'  => 'Võ Xuân Thanh',
            'acc_sex'       => '0',
            'acc_birthday'  => $faker->dateTimeBetween('1980-01-01','2000-01-01', null),
            'acc_phonenum'  => '0949621372',
            'acc_picture'   => 'avatar5.png',
            'acc_email'     => 'thanh292@gmail.com', 
            'rol_id'        => '2'],
        ["acc_user" => 'kien564', "acc_password" => $password,
            'acc_fullname'  => 'Đỗ Thanh Kiên',
            'acc_sex'       => '1',
            'acc_birthday'  => $faker->dateTimeBetween('1980-01-01','2000-01-01', null),
            'acc_phonenum'  => '0937623051',
            'acc_picture'   => 'avatar5.png',
            'acc_email'     => 'kien564@gmail.com', 
            'rol_id'        => '2'],
        
        ["acc_user" => 'phi361', "acc_password" => $password,
            'acc_fullname'  => 'Hồ Phi Phi',
            'acc_sex'       => '0',
            'acc_birthday'  => $faker->dateTimeBetween('1980-01-01','2000-01-01', null),
            'acc_phonenum'  => '0919931111',
            'acc_picture'   => 'avatar5.png',
            'acc_email'     => 'phi361@gmail.com', 
            'rol_id'        => '2'],
        ["acc_user" => 'minh432', "acc_password" => $password,
            'acc_fullname'  => 'Phạm Hiểu Minh',
            'acc_sex'       => '0',
            'acc_birthday'  => $faker->dateTimeBetween('1980-01-01','2000-01-01', null),
            'acc_phonenum'  => '0994764923',
            'acc_picture'   => 'avatar5.png',
            'acc_email'     => 'minh432@gmail.com', 
            'rol_id'        => '2'],
        ["acc_user" => 'lien999', "acc_password" => $password,
            'acc_fullname'  => 'Đỗ Hà Liên',
            'acc_sex'       => '0',
            'acc_birthday'  => $faker->dateTimeBetween('1980-01-01','2000-01-01', null),
            'acc_phonenum'  => '0955053210',
            'acc_picture'   => 'avatar5.png',
            'acc_email'     => 'lien999@gmail.com', 
            'rol_id'        => '2'],
        ["acc_user" => 'hien447', "acc_password" => $password,
            'acc_fullname'  => 'Phan Mai Hiền',
            'acc_sex'       => '0',
            'acc_birthday'  => $faker->dateTimeBetween('1980-01-01','2000-01-01', null),
            'acc_phonenum'  => '0952447705',
            'acc_picture'   => 'avatar5.png',
            'acc_email'     => 'hien447@gmail.com', 
            'rol_id'        => '2'],
        ["acc_user" => 'ha674', "acc_password" => $password,
            'acc_fullname'  => 'Phạm Mai Hà',
            'acc_sex'       => '0',
            'acc_birthday'  => $faker->dateTimeBetween('1980-01-01','2000-01-01', null),
            'acc_phonenum'  => '0921243797',
            'acc_picture'   => 'avatar5.png',
            'acc_email'     => 'ha674@gmail.com', 
            'rol_id'        => '2'],
        ["acc_user" => 'thuy407', "acc_password" => $password,
            'acc_fullname'  => 'Đặng Bảo Thúy',
            'acc_sex'       => '0',
            'acc_birthday'  => $faker->dateTimeBetween('1980-01-01','2000-01-01', null),
            'acc_phonenum'  => '0936123251',
            'acc_picture'   => 'avatar5.png',
            'acc_email'     => 'thuy407@gmail.com', 
            'rol_id'        => '2'],
        ["acc_user" => 'tien379', "acc_password" => $password,
            'acc_fullname'  => 'Phạm Cát Tiên',
            'acc_sex'       => '0',
            'acc_birthday'  => $faker->dateTimeBetween('1980-01-01','2000-01-01', null),
            'acc_phonenum'  => '0987004925',
            'acc_picture'   => 'avatar5.png',
            'acc_email'     => 'tien379@gmail.com', 
            'rol_id'        => '2'],
        ["acc_user" => 'khanh689', "acc_password" => $password,
            'acc_fullname'  => 'Võ Quang Khanh',
            'acc_sex'       => '1',
            'acc_birthday'  => $faker->dateTimeBetween('1980-01-01','2000-01-01', null),
            'acc_phonenum'  => '0997091257',
            'acc_picture'   => 'avatar5.png',
            'acc_email'     => 'khanh689@gmail.com', 
            'rol_id'        => '2'],
        ["acc_user" => 'duong998', "acc_password" => $password,
            'acc_fullname'  => 'Phạm Hải Dương',
            'acc_sex'       => '1',
            'acc_birthday'  => $faker->dateTimeBetween('1980-01-01','2000-01-01', null),
            'acc_phonenum'  => '0963676349',
            'acc_picture'   => 'avatar5.png',
            'acc_email'     => 'duong998@gmail.com', 
            'rol_id'        => '2'],
        ["acc_user" => 'dung465', "acc_password" => $password,
            'acc_fullname'  => 'Trần Quang Dũng',
            'acc_sex'       => '1',
            'acc_birthday'  => $faker->dateTimeBetween('1980-01-01','2000-01-01', null),
            'acc_phonenum'  => '0972381739',
            'acc_picture'   => 'avatar5.png',
            'acc_email'     => 'dung465@gmail.com', 
            'rol_id'        => '2'],
        ["acc_user" => 'vuong696', "acc_password" => $password,
            'acc_fullname'  => 'Nguyễn Kim Vượng',
            'acc_sex'       => '1',
            'acc_birthday'  => $faker->dateTimeBetween('1980-01-01','2000-01-01', null),
            'acc_phonenum'  => '0973259327',
            'acc_picture'   => 'avatar5.png',
            'acc_email'     => 'vuong696@gmail.com', 
            'rol_id'        => '2'],
        ["acc_user" => 'cuong391', "acc_password" => $password,
            'acc_fullname'  => 'Hồ Thịnh Cường',
            'acc_sex'       => '1',
            'acc_birthday'  => $faker->dateTimeBetween('1980-01-01','2000-01-01', null),
            'acc_phonenum'  => '0950982755',
            'acc_picture'   => 'avatar5.png',
            'acc_email'     => 'cuong391@gmail.com', 
            'rol_id'        => '2'],
        ["acc_user" => 'tuong689', "acc_password" => $password,
            'acc_fullname'  => 'Phạm Hữu Tường',
            'acc_sex'       => '1',
            'acc_birthday'  => $faker->dateTimeBetween('1980-01-01','2000-01-01', null),
            'acc_phonenum'  => '0934328401',
            'acc_picture'   => 'avatar5.png',
            'acc_email'     => 'tuong689@gmail.com', 
            'rol_id'        => '2'],
        ["acc_user" => 'son712', "acc_password" => $password,
            'acc_fullname'  => 'Hồ Danh Sơn',
            'acc_sex'       => '1',
            'acc_birthday'  => $faker->dateTimeBetween('1980-01-01','2000-01-01', null),
            'acc_phonenum'  => '0932741531',
            'acc_picture'   => 'avatar5.png',
            'acc_email'     => 'son712@gmail.com', 
            'rol_id'        => '2'],
        ["acc_user" => 'phuc981', "acc_password" => $password,
            'acc_fullname'  => 'Bùi Thế Phúc',
            'acc_sex'       => '1',
            'acc_birthday'  => $faker->dateTimeBetween('1980-01-01','2000-01-01', null),
            'acc_phonenum'  => '0992640977',
            'acc_picture'   => 'avatar5.png',
            'acc_email'     => 'phuc981@gmail.com', 
            'rol_id'        => '2'],
        ["acc_user" => 'son952', "acc_password" => $password,
            'acc_fullname'  => 'Dương Bằng Sơn',
            'acc_sex'       => '1',
            'acc_birthday'  => $faker->dateTimeBetween('1980-01-01','2000-01-01', null),
            'acc_phonenum'  => '0950463246',
            'acc_picture'   => 'avatar5.png',
            'acc_email'     => 'son952@gmail.com', 
            'rol_id'        => '2']   
       
        ];
        
        DB::table('account')->insert($list);
    }
}
